// Mirrors backend/app/schemas/common.py — keep these two in sync manually
// until we generate one from the other via the OpenAPI schema.

export type ComplianceStatus = 'compliant' | 'warning' | 'gap' | 'unknown'
export type GapStatus = 'open' | 'fix_generated' | 'pr_opened' | 'resolved'
export type PRStatus = 'ready_for_review' | 'awaiting_author' | 'merged' | 'closed'
export type RegulationCode = 'DPDP' | 'GDPR' | 'SOC2' | 'HIPAA'

export interface CommitRef {
  sha: string
  message: string
  author: string
  repo: string
  branch: string
  committed_at: string
}

// --- graph.py -----------------------------------------------------------

export interface GraphNode {
  id: string
  label: string
  node_type: string
  status: ComplianceStatus
  status_detail: string
  data_collected: string
  purpose: string
  retention: string
}

export interface GraphEdge {
  id: string
  source: string
  target: string
  relationship: string
}

export interface GraphResponse {
  nodes: GraphNode[]
  edges: GraphEdge[]
  // The node query is capped. These say how much of the graph you are
  // looking at, so a bounded view never passes for the whole thing.
  total_nodes: number
  node_limit: number
  truncated: boolean
  generated_at: string
}

// --- gaps.py --------------------------------------------------------------

export interface RemediationDraft {
  document: string
  summary: string
  file_path: string | null
  diff_text: string | null
}

export type GapSeverity = 'high' | 'medium' | 'low'
export type GapKind =
  // From the Act: is there an obligation covering this data type?
  | 'ungoverned_egress'
  | 'ungoverned_collection'
  | 'future_obligation'
  // From the company's own published documents: have we said we do this?
  | 'undisclosed_sharing'
  | 'undisclosed_collection'

export interface Gap {
  id: string
  title: string
  status: GapStatus
  // Written by the reconciler, dropped by the API until now.
  severity: GapSeverity | null
  kind: GapKind | null
  // "specific" when a clause names this data type, "general" when only
  // the Act's all-personal-data obligations reach it.
  coverage_basis: 'specific' | 'general' | 'none' | null
  source_commit: CommitRef | null
  source_file: string | null
  vendor: string | null
  data_types: string[]
  affected_documents: string[]
  regulations: RegulationCode[]
  ai_recommendation: string
  remediation_drafts: RemediationDraft[]
  // From the :PullRequest node in the graph, not the :Gap's own property.
  // A gap whose status says pr_opened but which carries no pull request is
  // reported as fix_generated by the API, so these three are either all
  // present or all null.
  pr_id: string | null
  pr_url: string | null
  pr_number: number | null
  detected_at: string
  updated_at: string
}

export interface GapsResponse {
  // null when there is nothing to score (empty graph) or the graph could
  // not be read -- render "not applicable", never a number.
  score: number | null
  // The sentence the backend writes to go with a null score. For a fresh
  // account this is "No repository scanned yet — nothing has been mapped
  // …", which is also how the UI knows the account has no data at all.
  score_explanation: string | null
  // null until a previous score exists to compare against.
  score_delta: number | null
  open_gap_count: number
  gaps: Gap[]
}

export interface GenerateFixResponse {
  gap_id: string
  remediation_drafts: RemediationDraft[]
}

// --- dashboard.py -----------------------------------------------------------

export interface StatCard {
  label: string
  value: string
  sub_label: string
  sub_tone: 'good' | 'warn' | 'neutral'
  // Why the value is what it is — set on the score card, and the only
  // thing there is to show when `value` is "—". A brand-new account gets
  // "No repository scanned yet …". Render this sentence; never fill the
  // gap with a number.
  score_explanation: string | null
}

export interface TimelineStep {
  title: string
  meta: string
  state: 'done' | 'active' | 'pending'
  tag: string | null
  tag_tone: 'warn' | 'wait' | null
}

export interface CommitActivity {
  commit: CommitRef
  has_compliance_impact: boolean
  // Only the illustrative samples carry a diff stat; a commit rebuilt
  // from :Gap provenance has no diff behind it.
  diff_stat: string
  // Gaps that trace back to this commit. Real and countable.
  gap_count: number
}

export interface DashboardSummaryResponse {
  stat_cards: StatCard[]
  timeline: TimelineStep[]
  recent_commits: CommitActivity[]
  synced_at: string
  // true when timeline/recent_commits are illustrative samples rather
  // than real events. Must be surfaced in the UI when set.
  sample_panels: boolean
}

// --- repos.py -----------------------------------------------------------

export interface Repository {
  id: string
  full_name: string
  branch: string
  private: boolean
  // null until the repository has actually been scanned. These used to be
  // required, which meant the API had to invent a score for every repo.
  score: number | null
  last_scanned_at: string | null
  status: ComplianceStatus | null
  status_detail: string | null
  pushed_at: string | null
}

export interface ReposResponse {
  repositories: Repository[]
  // true when the token can see more than were returned
  truncated: boolean
}

// --- vendors.py -----------------------------------------------------------

export interface Vendor {
  id: string
  name: string
  // null when the graph never recorded a category. Do not substitute a
  // placeholder like "Third Party" -- that asserts something unknown.
  category: string | null
  data_collected: string
  coverage_status: ComplianceStatus
  coverage_detail: string
  // true ONLY when a vendor-API ingestion actually ran against this
  // vendor. A name the code scanner spotted in source is not a connection.
  connection_active: boolean
  discovered_via: 'vendor_api' | 'code_scan'
}

export interface VendorsResponse {
  vendors: Vendor[]
}

// --- regulations.py ---------------------------------------------------------

export interface RegulationCoverage {
  code: RegulationCode
  // null for a framework that is listed but not enabled -- the backend
  // sends no score for those, and rendering the literal string "null" is
  // worse than rendering nothing.
  score_label: string | null
  enabled: boolean
  missing_requirements: string[]
  mapped_controls: string[]
  affected_systems: string[]
  // Next tranche of the Act that has not commenced yet, from
  // legal/commencement.py. null for frameworks with no schedule.
  next_commencement_date: string | null
  next_commencement_days: number | null
}

export interface RegulationsResponse {
  regulations: RegulationCoverage[]
}

// --- policies.py ------------------------------------------------------------

export interface Policy {
  id: string
  name: string
  status: ComplianceStatus
  status_label: string
  description: string
  coverage_percent: number
}

export interface PoliciesResponse {
  policies: Policy[]
}

// --- prs.py -------------------------------------------------------------

export interface PullRequest {
  id: string
  gap_id: string
  title: string
  repo_full_name: string
  status: PRStatus
  opened_by: string
  reviewer: string
  regulations: RegulationCode[]
  files: RemediationDraft[]
  github_pr_url: string | null
  opened_at: string
  updated_at: string
}

export interface PRsResponse {
  pull_requests: PullRequest[]
}

export interface OpenPRResponse {
  pull_request: PullRequest
}

// --- audit.py -------------------------------------------------------------

export interface AuditEvent {
  id: string
  occurred_at: string
  event_type: string
  title: string
  description: string
  actor: string
}

export interface AuditResponse {
  events: AuditEvent[]
}

// --- github.py (connection + OAuth) ---------------------------------------
// GitHub access is per user now: each account connects its own GitHub
// account, and every repository read or pull request is made with that
// person's token. There is no shared instance token any more.

/** How the stored credential was obtained. */
export type GitHubConnectMethod = 'oauth' | 'token'

export interface GitHubConnection {
  connected: boolean
  login: string | null
  avatar_url: string | null
  scopes: string[]
  method: GitHubConnectMethod | string | null
  connected_at: string | null
}

export interface GitHubOAuthStartResponse {
  authorize_url: string
  state: string
}

export interface GitHubDisconnectResponse {
  connected: boolean
  // false is not a failure — it means there was nothing stored to remove.
  removed: boolean
  message: string
}

/**
 * The `reason` slug on `/repositories?github=error&reason=…`. These are
 * machine words for the frontend only; every one of them is translated
 * into a plain sentence before it reaches a person (see
 * lib/githubMessages.ts).
 */
export type GitHubOAuthErrorReason =
  | 'missing_code'
  | 'invalid_state'
  | 'github_unreachable'
  | 'exchange_failed'
  | 'validation_failed'
  | 'storage_failed'
  | 'graph_unavailable'
  | 'oauth_not_configured'

// --- workspace.py -----------------------------------------------------------
// What this ACCOUNT has scanned, which is a different set from
// /github/repos (what exists on GitHub). A repository can be listed here
// and no longer exist on GitHub, or exist on GitHub and never have been
// scanned; the two lists answer different questions and are fetched
// separately.

export interface ScannedRepository {
  /**
   * The graph's key for this repository, and the only thing the delete
   * call needs. It is a slug (`owner__repo`) and must never be rendered —
   * `repo` is the name a person recognises.
   */
  system_name: string
  /** `owner/repo`, as GitHub spells it. This is what the UI shows. */
  repo: string
  data_types: number
  vendors: number
  gaps: number
  /**
   * null when the repository was loaded by a command-line run rather than
   * scanned through the app. Not an error and not "never scanned" — say so
   * in words rather than leaving the column blank.
   */
  last_scan: string | null
}

export interface ScannedRepositoriesResponse {
  repositories: ScannedRepository[]
}

/**
 * What a removal actually deleted, counted by the server after the fact.
 *
 * Every field is optional because the two operations report different
 * shapes: removing one repository returns `system` (always 1), a reset
 * returns `systems` (how many repositories went). Rendering these is the
 * only honest way to confirm a destructive action — a fixed "Removed."
 * would claim the same thing whether eleven findings went or none did.
 */
export interface RemovalCounts {
  drafts?: number
  pull_requests?: number
  gaps?: number
  scans?: number
  policy_documents?: number
  system?: number
  systems?: number
  data_types?: number
  vendors?: number
}

export interface RemovalResponse {
  /** The repository that was removed. null for a whole-account reset. */
  repo: string | null
  system_name: string | null
  removed: RemovalCounts
  /** Set only by the reset. null for a single-repository removal. */
  reset_at: string | null
}
